### ISSUE TITLE
Offering help

### ISSUE THREAD

**Issue by Sturla22** [AllYarnsAreBeautiful/ayab-firmware#19]
Hello!
I've been looking through the code and issues in this repository and am wondering if there is anything specific that is prioritized that the community would like help with?

I have a few ideas of my own for improvements but would like to work on something that the community is interested in.

**My ideas**

- [x] Formatting with clang-format for a more uniform formatting style (#20)
- [x] Adding host-side unit tests to make refactoring and reviewing easier (#22)
- [x] Using more C++ features, like constexpr and namespaces (#30)
- [x] Binary releases ( related to #5 ) that may then be made a part of the desktop application (i.e. an update FW button or even auto updating FW to match the desktop version)

If there is any preference for what work needs to be done and, maybe more importantly, what kind of pull requests will be accepted, it would be interesting to hear about those.

Kind regards,
Sturla

**Comment by chris007de** [comment]
Hi,
thanks a lot for your offer!
Speaking in general, every help and contribution is very appreciated. Both the firmware and the desktop software need some :heart: . So I suggest to just pick a topic you like, write an issue describing the changes you intend to do and start coding :)
Clang-format and unit tests would be my personal favorites to start with, as these would be a good base for further improvements and changes on the code.

Chris
